site_name: RPL Peptide Laboratory Documentation Handbook

site_description: Research peptide technical documentation, specification sheets, COA and laboratory resources

theme:
  name: material

nav:
  - Home: index.md

  - Products:
      - Product Documentation: products/index.md

  - Technical Sheets:
      - Technical Documentation: tech-sheets/index.md

  - Certificates:
      - Certificates: certificates/index.md

  - FAQ:
      - FAQ: faq/index.md

  - Glossary:
      - Peptide Glossary: glossary/index.md


plugins:
  - search


markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - footnotes